package liangliang.study.red.envelops.mapper;

import liangliang.study.red.envelops.entity.RedDetail;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface RedDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_detail
     *
     * @mbg.generated Mon Aug 17 22:40:12 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_detail
     *
     * @mbg.generated Mon Aug 17 22:40:12 CST 2020
     */
    int insert(RedDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_detail
     *
     * @mbg.generated Mon Aug 17 22:40:12 CST 2020
     */
    int insertSelective(RedDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_detail
     *
     * @mbg.generated Mon Aug 17 22:40:12 CST 2020
     */
    RedDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_detail
     *
     * @mbg.generated Mon Aug 17 22:40:12 CST 2020
     */
    int updateByPrimaryKeySelective(RedDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_detail
     *
     * @mbg.generated Mon Aug 17 22:40:12 CST 2020
     */
    int updateByPrimaryKey(RedDetail record);
}