package liangliang.study.red.envelops.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class RedDetail implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_detail.id
     *
     * @mbg.generated Mon Aug 17 22:40:12 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_detail.record_id
     *
     * @mbg.generated Mon Aug 17 22:40:12 CST 2020
     */
    private Integer recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_detail.amount
     *
     * @mbg.generated Mon Aug 17 22:40:12 CST 2020
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_detail.is_active
     *
     * @mbg.generated Mon Aug 17 22:40:12 CST 2020
     */
    private Byte isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_detail.create_time
     *
     * @mbg.generated Mon Aug 17 22:40:12 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table red_detail
     *
     * @mbg.generated Mon Aug 17 22:40:12 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_detail.id
     *
     * @return the value of red_detail.id
     *
     * @mbg.generated Mon Aug 17 22:40:12 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_detail.id
     *
     * @param id the value for red_detail.id
     *
     * @mbg.generated Mon Aug 17 22:40:12 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_detail.record_id
     *
     * @return the value of red_detail.record_id
     *
     * @mbg.generated Mon Aug 17 22:40:12 CST 2020
     */
    public Integer getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_detail.record_id
     *
     * @param recordId the value for red_detail.record_id
     *
     * @mbg.generated Mon Aug 17 22:40:12 CST 2020
     */
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_detail.amount
     *
     * @return the value of red_detail.amount
     *
     * @mbg.generated Mon Aug 17 22:40:12 CST 2020
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_detail.amount
     *
     * @param amount the value for red_detail.amount
     *
     * @mbg.generated Mon Aug 17 22:40:12 CST 2020
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_detail.is_active
     *
     * @return the value of red_detail.is_active
     *
     * @mbg.generated Mon Aug 17 22:40:12 CST 2020
     */
    public Byte getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_detail.is_active
     *
     * @param isActive the value for red_detail.is_active
     *
     * @mbg.generated Mon Aug 17 22:40:12 CST 2020
     */
    public void setIsActive(Byte isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_detail.create_time
     *
     * @return the value of red_detail.create_time
     *
     * @mbg.generated Mon Aug 17 22:40:12 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_detail.create_time
     *
     * @param createTime the value for red_detail.create_time
     *
     * @mbg.generated Mon Aug 17 22:40:12 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}