package liangliang.study.red.envelops.service;

import liangliang.study.red.envelops.entity.RedRobRecord;

public interface RedRobRecordService {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_rob_record
     *
     * @mbg.generated Mon Aug 17 22:40:12 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_rob_record
     *
     * @mbg.generated Mon Aug 17 22:40:12 CST 2020
     */
    int insert(RedRobRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_rob_record
     *
     * @mbg.generated Mon Aug 17 22:40:12 CST 2020
     */
    int insertSelective(RedRobRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_rob_record
     *
     * @mbg.generated Mon Aug 17 22:40:12 CST 2020
     */
    RedRobRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_rob_record
     *
     * @mbg.generated Mon Aug 17 22:40:12 CST 2020
     */
    int updateByPrimaryKeySelective(RedRobRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_rob_record
     *
     * @mbg.generated Mon Aug 17 22:40:12 CST 2020
     */
    int updateByPrimaryKey(RedRobRecord record);

}
